### PR TITLE
[WIP] Use enc 2 to shift sequences left/right

### PR DESCRIPTION
**Pull request by tildebyte**

### CODE REVIEW

**Comment by tildebyte** [comment]
Sorry about the messy diff in commit 2de7225; git can be a little stupid sometimes.

@justmat; Can't add you as a reviewer... so pinging you here: can you PTAL?

@justmat, @millxing; This works as-is and is kinda cool, but I have two open issues:

1. Do we agree that this is desirable UX? Discussion below...
1. Is there something I can do to make it less "twitchy". I had the idea of using a local to grab the enc delta and increment up to 2-3 "ticks" before actually firing the shift, but I haven't tried it yet.

UX/UI - I have a working prototype where enc 2 shifts sequences L/R (this PR), and enc 3 changes the sequence length, while playing, without resetting playback (not fully baked; I'll be opening another WIP PR for help with that one). Both of these changes together allow for interesting on-the-fly changes not obtainable otherwise.

This is actually really cool/fun, but I don't know if @millxing will like the idea or not :)

Where I'm getting stuck from a design standpoint (assuming that this is a good idea) is; should enc 1 shift the notes (row 2), or (for lack of a better term) the "playhead sequence" (row 1)? It doesn't make sense if the "playhead sequence" is 16 notes, but when it's shorter (particularly when fairly short), it would be cool to "slide" the shorter "playhead sequence" over a set of notes, while also being able to tweak it's length...

This came up while I was playing with what I currently have, and realized that changing the "playhead sequence" **didn't** change the note sequence - it's being preserved at all times.

n.b. this doesn't interfere/interact with the current length/shift functionality at all; that's all preserved as-is.

**Comment by millxing** [comment]
I like Encoder 2 shifting the sequence. Maybe adding Encoder 3 to control the transpositions. Not sure why I didn't use the encoders originally. I think I may have just wanted to keep those free in case I had something else to use there.

Not sure about the other ideas re: the playhead, but I'd definitely be open to it.

**Comment by justmat** [comment]
Haven't had a chance to take a look yet, but for making the encoder less twitchy you can use ``norns.encoder.sens(enc_id, value)`` and maybe turn off encoder acceleration with ``norns.encoder.accel(encoder_id, false)``.

**Comment by tildebyte** [comment]
@millxing, @justmat; I'm utterly baffled. This is the second code-staring session I've undertaken to try to figure this out, and I don't have a clue.

When I resize the sequence length to be *shorter*, the grid doesn't update correctly until I switch pages; when I resize the sequence length to be *longer*, it updates immediately...

**Pull request merged**
