### PR TITLE
Reversed sequences now *play* in reverse...

### PR DESCRIPTION
**Pull request by tildebyte**
...instead of actually reversing the sequence.
Maybe this is a performance boost  ¯\_(ツ)_/¯? Either way, it *looks* cool :)
Closes issue #4

### CODE REVIEW

**Comment by tildebyte** [comment]
@millxing Looking for review/comments/testing. It's hard for me to believe that this actually worked as I expected it to, first try, with no side-effects >_<

**Comment by millxing** [comment]
How do I get a copy of your new version (with new reverse) to try it out before confirming?

**Comment by millxing** [comment]
I can see the changes but they are alongside the original version. How do I get a clean copy of the new branch to load into maiden?

**Comment by tildebyte** [comment]
Sorry, I buggered up my commit history for a minute.
You'll ssh into norns, and change to the QUENCE directory.
From there, you'll `git remote add tildebyte https://github.com/tildebyte/QUENCE.git` (I hope that's right >_<) to add my repo as a new remote named 'tildebyte'.
Then, `git fetch --all` to pull a list of available branches on all remotes.
Then `git checkout tildebyte/reverse-playback-display` *should* switch you to my dev branch named 'reverse-playback-display'
Ping me here if you run into trouble.

**Comment by millxing** [comment]
I was able to copy the code from your repo and paste it into maiden. 

It does look cool! But it's not working correctly when it's reversing back around (going from step 1 to step 16). It seems to treat steps 15 and 16 like rest notes.

I'm going out until later tonight and then off on a ski trip tomorrow. Not sure when I'll get a chance to help you debug it, but hopefully I'll get a chance to work on it tonight.

**Comment by tildebyte** [comment]
> It seems to treat steps 15 and 16 like rest notes.
Yeah, dang it. Not sure what's going on there, but I hope to have some time to debug tonight.

**Comment by tildebyte** [comment]
Fixed. Modulo math over reverse sequence 😵.
Don't know what I'd do without stackoverflow.
(also kinda needs to be per-track derp)

**Pull request merged**
