### PR TITLE
Init/reset sequences at zero instead of 16

### PR DESCRIPTION
**Pull request by tildebyte**
also rename "local_x" -> "track"; I finally figured out what it's for >_<

@millxing;  Optional: feel free to disregard if you don't agree

### CODE REVIEW

**Comment by millxing** [comment]
I thought that if you initialize sequences to 1, then the first note played will be the second step, not the first step. That's why I initialized on the 16th step, not the first. Or am I missing something?

**Comment by tildebyte** [comment]
> I thought that if you initialize sequences to 1, then the first note played will be the second step,
> not the first step. That's why I initialized on the 16th step, not the first. Or am I missing something?

Ohhh, that might be. Let me verify.

**Comment by tildebyte** [comment]
OK, absolutely correct.
Initting/resetting to '0' seems to work (good ole' crazy-head Lua)
@millxing; Would you mind taking a look at commit af421a9, replacing the '1' with '0' and see how it works for you? I think it's an OK solution to an odd issue (script starts up with the playhead light at the end of the sequence); OTOH init to '0' means the script starts up with no playhead lighted :P

**Comment by millxing** [comment]
Not sure how to handle this branch conflict.

**Comment by tildebyte** [comment]
The branch conflict is on me to resolve.

**Comment by millxing** [comment]
Yup. I think that did the trick (initializing at zero). Nice work!

**Pull request merged**
